import React, { useState } from 'react'
import logo from '../images/onlocation.png'

export function Home() {
  return (
    <>
      <header>
        <div className="title">
          <img src={logo} />
        </div>

        <div className="social">
          <ul>
            <li>facebook</li>
            <li>twitter</li>
            <li>join</li>
            <li>sign in</li>
          </ul>
        </div>
      </header>
      <main>
        <h1>Welcome to On Location</h1>
        <input type="text" placeholder="Search..." />
        <section>
          <h2>New York</h2>
          <ul>
            <li>
              <img
                src="https://theposterdb.com/api/assets/23880"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/36537"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/35174"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/5918"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/35901"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/560"
                width="210"
                height="315"
              ></img>
            </li>
          </ul>
        </section>
        <section>
          <h2>New Orleans</h2>
          <ul>
            <li>
              <img
                src="https://theposterdb.com/api/assets/88381"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/8609"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/77118"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/64096"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/2629"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/41482"
                width="210"
                height="315"
              ></img>
            </li>
          </ul>
        </section>
        <section>
          <h2> Martin Scorsese</h2>
          <ul>
            <li>
              <img
                src="https://theposterdb.com/api/assets/54268"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/54275"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/47512"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/9316"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/81198"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/50890"
                width="210"
                height="315"
              ></img>
            </li>
          </ul>
        </section>
        <section>
          <h2>David Fincher</h2>
          <ul>
            <li>
              <img
                src="https://theposterdb.com/api/assets/66490"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/64096"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/28666"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/55575"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/27354"
                width="210"
                height="315"
              ></img>
            </li>
            <li>
              <img
                src="https://theposterdb.com/api/assets/31579"
                width="210"
                height="315"
              ></img>
            </li>
          </ul>
        </section>
      </main>
      <footer>
        <p>about</p>
        <p>contact us</p>
        <p>home</p>
        <p>Designed by</p>
      </footer>
    </>
  )
}
