TRUNCATE TABLE "Locations"
, "Reviews" RESTART IDENTITY;
TRUNCATE TABLE "Films";
TRUNCATE TABLE "Users";


INSERT INTO "Users" ("Id", "FullName", "Email") VALUES ('1', 'Test', 'a@b.com');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('The Brody House', 'The house featured in the production has been completely renovated, but this is still Chief Martin Brodys address.', '265 East Chop Dr Vineyard Haven, Mass.', 'Jaws', '1', '41.470250', '-70.570340');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Amity Police Department', 'Where Brody Types up the "shark Attack" police report', 'South Water Street & Davis Lane Edgartown, MA 02539', 'Jaws', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Amity Hardware', 'Brody grabs supplies for his "Beach Closed" mission at Amity Hardware and then walks through the center of town.', 'South Water Street & Main Street Edgartown, Mass.', 'Jaws', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('The Beach', 'Where Alex Kitner is eaten', 'Joseph Sylvia State Beach Oak Bluffs, Mass.', 'Jaws', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('The Bridge', 'Bridge from beach to pond', 'American Legion Memorial Bridge', 'Jaws', '1', '41.4161', '70.5487');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Quint Shack', 'While his workshop was built for the production and no longer standing, the adorable fishing village/tourist haven of Menemsha remains', 'Menemsha Port Chilmark, Mass.', 'Jaws', '1', '41.347680', '-70.744020');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Amity Town Hall', 'Interior and eterior of Amity town hall', ' 70 Main Street Edgartown, Mass.', 'Jaws', '1', '41.389640', '-70.514740');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Vaughn Realty', 'Mayor Vaughn exterior location', '1 Water Street Edgartown, Mass.', 'Jaws', '1', '41.3892442', '-70.5479281');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('The Opening Scene', 'Beach bonfire and the demise of Chrissie Watkins.', 'South Beach Edgartown, Mass', 'Jaws', '1', '41.206150', '-86.594520');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Keisel Bicycle Rental & Amity Gazette', 'The Gazette and Bicycle rental are located across from oneanother. Shop owner complains about kids karate chopping fences', '2 South Water Street Edgartown, MA 02539', 'Jaws', '1', '41.3893657', '-70.5833555');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Chappy Ferry', 'The ferry worked as both a principal camera boat for the production and starred in the scene where Brody is browbeaten by the mayor into keeping the beaches open for the Fourth. You know, for the tourists. "Martin, its all psychological. You yell barracuda, everybody says, "Huh? What?" You yell shark, weve got a panic on our hands on the Fourth of July."', '53 Dock Street Edgartown, MA 02539', 'Jaws', '1', '41.3892155', '-70.514312');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Billboard/Lighthouse', 'Where Brody and Vaughn argue about keeping beaches open', '35 Aquinnah Circle Aquinnah, MA 02535', 'Jaws', '1', '41.3461722', '-70.9055635');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Wacker Drive', 'A major multilevel 2.2 mile stretch in lower Chicago, running along the south side of the main branch and the east side of the south branch of the Chicago River in the Loop.', '233 E Wacker Dr, Chicago, IL 60601', 'The Dark Knight', '1', '41.8877172', '-87.691257');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('The Old Main Post Office', 'Used in Batman Begins and The Dark Knight as Gotham Police Department', '433 W Van Buren St, Chicago, IL 60607', 'The Dark Knight', '1', '41.8755587', '-87.7088813');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Chicago Board of Trade', 'The Chicago Board of Trade building is an iconic Art Deco skyscraper on West Jackson Boulevard. In film, it stood in as Bruce Wayne’s corporate HQ in Batman Begins. One of its trading floors was shown in Ferris Buellers day Off, also featured in several scenes in The Untouchables.', '141 W Jackson Blvd, Chicago, IL 60604', 'The Dark Knight', '1', '41.8780309', '-87.6367784');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Art Institute of Chicago', 'Ferris and his friends take on the streets of Chicago, with a drop-by at the Art Institute of Chicago.', '111 S Michigan Ave, Chicago, IL 60603', 'Ferris beullers Day Off', '1', '41.8795473', '-87.6259125');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Union Station', 'As one of Chicago’s most iconic and historical landmarks, Union Station serves as backdrop to various scenes in movie history. It’s the citys primary terminal for commuter trains, covering over 9 city blocks underneath Chicago’s network of streets and skyscrapers.', '225 S Canal St, Chicago, IL 60606', 'The Untouchables', '1', '41.8785772', '-87.6418552');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Wrigley Field', 'Wrigley Field is promently featured in several films, such as Ferris Beullers Day Off, A League of Their Own, and Rookie of the Year', '1060 W Addison St, Chicago, IL 60613', 'A League of Their Own', '1', '41.9474552', '-87.6604312');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('The Fireside Bowl', ' The retro-styled bowling alley has not only hosted serious bowlers for ages, it was also the nexus of Chicago’s punk scene for many years. It is featured in The Break Up', 'S2646 W Fullerton Ave, Chicago, IL 60647', 'The Break Up', '1', '41.9248404', '-87.7092263');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('South LaSalle St', 'Transformed, and featured in the period piece Road to Perdition', 'S LaSalle St Chicago, IL', 'Road to Perdition', '1', '41.8770717', '-87.6405164');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('New York Public Library', 'Prominently feature in Ghostbusters, The Day After Tomorrow, Breakfast at Tiffanys Sex and the City: the Movie and Spider-Man', '476 Fifth Avenue, Manhattan, New York', 'Ghostbusters', '1', '40.7531903', '-73.9866308');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Times Square', 'Featured in numerous films, Taxi Driver, Midnight Cowboy, Date Night, Captain America, Big, Shaft, A Chorus Line, Vanilla Sky, Birdman… ', 'Manhattan, NY 10036', 'Taxi Driver', '1', '40.7580836', '-74.0555823');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Hook and Ladder 8', 'Who you gonna call?', '14 N Moore St, New York, NY 10013', 'Ghostbusters', '1', '40.7196745', '-74.0766521');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Grand Central Terminal', 'A transportation hub for travellers and commuters since 1913, Grand Central Terminal has been featured in numerous films such as, Carlitos way, The Avengers, and North by Northwest', '89 E 42nd St, New York, NY 10017', 'The Avengers', '1', '40.7528366', '-74.047275');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Captain Spauldings Museum', 'Captain Spauldings,  "Museum of Monsters and Madmen" was filmed at the Four Aces Movie Ranch in Palmdale California', 'Four Aces Movie Ranch, 14499 E Ave Q, Palmdale, CA 93591', 'House of 1000 Corpses', '1', '' , '');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('The Firefly House', 'Movie Set built on Universal Studios Lot', '100 Universal City Plaza, Universal City, CA 91608', 'House of 1000 Corpses', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('TS and Brandi get married', 'At the end of the film TS and Brandi are married on the Jaws ride at Universal Studios', '100 Universal City Plaza, Universal City, CA 91608', 'Mallrats', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Brandi house', 'Where TS tries to pick up his Girlfrind for vacation and fails', '414 S Rimpau Blvd, Los Angeles, CA 90020', 'Mallrats', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Marty Mcflys House', 'Marty Mcflys home in 1985', '9303 Roslyndale Ave, Pacoima, CA 91331', 'Back to the Future', '1', '41.470250', '-70.570340');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Doc Browns Home', 'Doc Browns home in 1955 and 1985', '4 Westmoreland Pl, Pasadena, CA 91103', 'Back to the Future', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Burger King', 'Burger King where Marty Hitches a ride on his Skateboard.', '535 N Victory Blvd, Burbank, CA 91502', 'Back to the Future', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Hill Valley Highschool', 'Highschool Marty, his parents and Biff attend', '12417 Philadelphia St, Whittier, CA 90601', 'Back to the Future', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Diner', 'Opening scene couple drives here, and the girl suggests they go someplace more quiet.', 'Puente Hills Mall, 1600 S Azusa Ave, City of Industry, CA 91748', 'Back to the Future', '1', '41.470250', '-70.570340');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('George Mcfly House', 'Martys fathers house in 1955', '1711 Bushnell Ave, South Pasadena, CA 91030', 'Back to the Future', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Lorraines House', 'Martys Mothers house in 1955.', '1727 Bushnell Ave, South Pasadena, CA 91030', 'Back to the Future', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Biffs Grandmothers House', 'Exterior of Biffs house in 1955', '1809 Bushnell Ave, South Pasadena, CA 91030', 'Back to the Future', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Courthouse square and clocktower', 'Both filmed on set at Universal Studios Hollywood', '100 Universal City Plaza, Universal City, CA 91608', 'Back to the Future', '1', '41.4161', '70.5487');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Opening Shot', 'Baby waiting outside the bank for the robbery to be over', '127 Peachtree St NE, Atlanta, GA 30303', 'Baby Driver', '1', '41.347680', '-70.744020');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Opening Titles Start', 'Baby Exits Healey Bulding and begins his walk', ' 57 Forsyth St NW, Atlanta, GA 30303', 'Baby Driver', '1', '41.389640', '-70.514740');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Coffee Shop', 'Where Baby buys Coffeee and first see Debora', '85 Poplar St NW, Atlanta, GA 30303', 'Baby Driver', '1', '41.3892442', '-70.5479281');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Uncle Chuckys Diner', 'Where Debora works and has her first conversation with Baby.', '5116 GA-85, Forest Park, GA 30297', 'Baby Driver', '1', '41.206150', '-86.594520');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Second Bank Robery', 'North of Downtown Atlanta, currently Vacant', '84 Perimeter Center E, Atlanta, GA 30346', 'Baby Driver', '1', '41.3893657', '-70.5833555');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Post Office', 'Baby and Doc plan next potential heist.', '30 Courtland St SE, Atlanta, GA 30303', 'Baby Driver', '1', '41.3892155', '-70.514312');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Climax', 'The end of the film was shot at the Jerry Wadley Memorial Bridge', 'Jerry Wadley Memorial Bridge, Juliette, GA 31046', 'Baby Driver', '1', '41.3461722', '-70.9055635');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Marcus House', 'Where Marcus Lives in first Film', '737 NW 15th Ave, Miami, FL 33125', 'Bad Boys', '1', '' , '');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Police Station', 'Dade Count courthouse', '73 W Flagler St, Miami, FL 33130', 'Bad Boys', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Club Hell', 'Marcus gets into a brawl in the bathroom', '471 NW 3rd St, Miami, FL 33128', 'Bad Boys', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Mikes Apartment', 'The apartment exterior where will smiths caracter lives', '2030 Park Ave, Miami Beach, FL 33139', 'Bad Boys', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Johnny Tapia Estate', 'Filmed at Vizcaya Museum and Gardens', '3251 S Miami Ave, Miami, FL 33129', 'Bad Boys II', '1', '41.470250', '-70.570340');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Miami Bank', 'Car chase where bodies in fall out of coffins.', '570 NE 81st St, Miami, FL 33138', 'Bad Boys II', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Mortuary', 'Macarthur Dairy Bulding, Mike and Marcus break in here.', '6851 NE 2nd Ave, Miami, FL 33138', 'Bad Boys II', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Opening Shot', 'Begins with a guitarist and drummer in front of a tree', '400 NW 73rd Ave, Plantation, FL 33317', 'There’s Something About Mary', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('HighSchool', 'Plantation City Hall was used for exterior shots of the school.', '400 NW 73rd Ave, Plantation, FL 33317', 'There’s Something About Mary', '1', '41.470250', '-70.570340');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Marys House', 'Located in Coral Gables Fl, where the notorious "zipper incident" happens', '3300 Granada Blvd, Coral Gables, FL 33134', 'There’s Something About Mary', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Outside Marys workplace ', 'Where Ted finds Mary years later and hides behind sculpture.', '701 Brickell Ave, Miami, FL 33131', 'There’s Something About Mary', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Hair Gel Scene', 'Where Mary meets Ted for their Date', '1300 Ocean Dr, Miami Beach, FL 33139', 'There’s Something About Mary', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Closing Shots', 'Ted and Mary stand here facing the water', 'NE 20th Terrace / N Bayshore Dr, Miami, FL 33137', 'There’s Something About Mary', '1', '41.4161', '70.5487');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Birdcage Club', 'The Carlyle was used for the Club in the film', '1250 Ocean Dr, Miami Beach, FL 33139', 'The Birdcage', '1', '41.347680', '-70.744020');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Ending Conversation', 'The ending was filmed at Jimmys Eastside Diner', '7201 Biscayne Blvd, Miami, FL 331383', 'Moonlight', '1', '41.389640', '-70.514740');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Opening Shot', 'Reseda Theater where the opening was filmed', '18443 Sherman Way, Reseda, CA 91335', 'Boogie Nights', '1', '41.3892442', '-70.5479281');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Hot Traxx nightclub', 'Nightclub wher Rollegirl and Dirk works.', '18419 Sherman Way, Reseda, CA 91335', 'Boogie Nights', '1', '41.206150', '-86.594520');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Dirks Parents House', 'Located in Torrance California', '3503 187th St, Torrance, CA 90504', 'Boogie Nights', '1', '41.3893657', '-70.5833555');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Du-Pars Restaurant', 'Jack Horder takes Dirk here for a meal with Amber and Rollergirl.', '12036 Ventura Blvd, Studio City, CA 91604', 'Boogie Nights', '1', '41.3892155', '-70.514312');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Jack Horners House', 'Several scenes shot here for the film', '19515 E Cameron Ave, Covina, CA 91724', 'Boogie Nights', '1', '41.3461722', '-70.9055635');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Dirk Digglers House', 'Dirk Moves here and thros a party', '4214 Lobos Rd, Woodland Hills, CA 91364', 'Boogie Nights', '1', '41.470250', '-70.570340');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Man in the Truck', 'Dirk, Down on his luck, solicits himself for money, and is attacked', '18128 Sherman Way, Reseda, CA 91335', 'Boogie Nights', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Miss Donuts', 'Buck Swope picks up Donuts.', '18231 Sherman Way, Reseda, CA 91335', 'Boogie Nights', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Robbery', 'Planned from the El Royale hotel', '11117 Ventura Blvd, Studio City, CA 91604', 'Boogie Nights', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Diner', 'Opening scene couple drives here, and the girl suggests they go someplace more quiet.', '4390 Atlantic Ave, Long Beach, CA 90807', 'Zodiac', '1', '41.470250', '-70.570340');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('San Francisco Chronicle', 'Robert Graysmiths place of employment as a cartoonist', '901 Mission St, San Francisco, CA 94103', 'Zodiac', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Cornerof Washington and Cherry', 'The film used the actual location of the murder.', '3893 Washington St, San Francisco, CA 94118', 'Zodiac', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('School bus', 'Robert hesitates to drop his son off at the school bus after the Zodiac warning', '908 Douglas St, Los Angeles, CA 90026', 'Zodiac', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Riverside Police Department', 'Paul Avery has an argument with Dave Toschi. ', '4130 Overland Ave, Culver City, CA 90230', 'Zodiac', '1', '41.4161', '70.5487');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Transamerica Pyramid building', 'Timelapse of the building being constructed to signify the passage of time', '600 Montgomery St, San Francisco, CA 94111', 'Zodiac', '1', '41.347680', '-70.744020');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Earl Warren Building ', 'Robert approaches Toschi, Toschi tells Robert not to disturb him anymore', '350 McAllister St, San Francisco, CA 94102', 'Zodiac', '1', '41.389640', '-70.514740');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Mills meets Somerset', 'In the opening of the film Mills meets his new partner in the flower district', '746 1/2 San Pedro St, Los Angeles, CA 90014', 'Se7en', '1', '41.3892442', '-70.5479281');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Gluttony', 'The beginning of the seven deadly sins murders.', '720 Beacon Ave, Los Angeles, CA 90017', 'Se7en', '1', '41.206150', '-86.594520');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Library', 'Somerset does reaserh to determine the motivation of the killer', '650 S Spring St, Los Angeles, CA 90014', 'Se7en', '1', '41.3893657', '-70.5833555');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Millennium Biltmore Hotel', 'Mills runs across the street in the rain.', '530 S Grand Ave, Los Angeles, CA 90071', 'Se7en', '1', '41.3892155', '-70.514312');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Sloth', 'Pan American Building the side of the building is seen in the film', '253 S Broadway, Los Angeles, CA 90012', 'Se7en', '1', '41.3461722', '-70.9055635');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Wild Bills Leather', 'Downtown Los Angeles', '123 E 6th St, Los Angeles, CA 90013', 'Se7en', '1', '' , '');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Police Station', 'Exterior shots of the Station', '673 Mateo St, Los Angeles, CA 90021', 'Se7en', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Whats in the box', 'The climax of the film was shot here', '10482 W Ave I, Lancaster, CA 93536', 'Se7en', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Support Groups', 'Edward Norton attends several support group meetings here', '310 S Van Ness Ave, Los Angeles, CA 90020', 'Fight Club', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Laundromat', 'Where "Narrator" confronts Marla and she steals clothes', '4371 Melrose Ave, Los Angeles, CA 90029', 'Fight Club', '1', '41.470250', '-70.570340');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Selling Stolen Clothes', 'Marla sells the stolen clothes from the laundromat.', '4314 Melrose Ave, Los Angeles, CA 90004', 'Fight Club', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Narrators apartment', 'Edward Nortons apartment from the beginning of the film.', '123 S Figueroa St, Los Angeles, CA 90012', 'Fight Club', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Tire Shop', 'One of the Club members sprays a man with a hose', '505 N Avalon Blvd, Wilmington, CA 90744', 'Fight Club', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Exterior Fight', 'One of the Impromptu fights happens here in front of the art.', '444 S Flower St, Los Angeles, CA 90071', 'Fight Club', '1', '41.470250', '-70.570340');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Millennium Biltmore Hotel ', 'Multiple scenes are filmed here for the film, including the waiter "cut off his balls" scene in the restroom', '506 S Grand Ave, Los Angeles, CA 90071', 'Fight Club', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Marlas Residence ', 'Marla lives in the Hotel Bristol.', '23 W 8th St, Los Angeles, CA 90014', 'Fight Club', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Computer Store ', 'This store is blown up near the Millenium Biltmore Hotel', '501 W 6th St, Los Angeles, CA 90014', 'Fight Club', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Lanaux Mansion', 'Benjamin Button is born here', '547 Esplanade Ave, New Orleans, LA 70116', 'The Curious Case of Benjamin Button', '1', '41.4161', '70.5487');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Nolan House', 'The house where Benjamin lives and meets Daisy', '2707 Coliseum St, New Orleans, LA 70130', 'The Curious Case of Benjamin Button', '1', '41.347680', '-70.744020');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Conversation on the Water', 'Mr Oti and Benjamin have a conversation here', '42 Dreyfous Dr, New Orleans, LA 70119', 'The Curious Case of Benjamin Button', '1', '41.389640', '-70.514740');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Audubon Park', 'Daisy dances for Benjamin here', 'Newman Bandstand, Golf Club Dr, New Orleans, LA 70118', 'The Curious Case of Benjamin Button', '1', '41.3892442', '-70.5479281');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Thirsty Scholar Pub', 'The opening conversation in the film about finals clubs takes place here.', 'Thirsty Scholar Pub, 70 Beacon St, Somerville, MA 02143', 'The Social Network', '1', '41.206150', '-86.594520');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Dirks Parents House', 'Located in Torrance California', '3503 187th St, Torrance, CA 90504', 'Boogie Nights', '1', '41.3893657', '-70.5833555');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Du-Pars Restaurant', 'Jack Horder takes Dirk here for a meal with Amber and Rollergirl.', '12036 Ventura Blvd, Studio City, CA 91604', 'Boogie Nights', '1', '41.3892155', '-70.514312');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Jack Horners House', 'Several scenes shot here for the film', '19515 E Cameron Ave, Covina, CA 91724', 'Boogie Nights', '1', '41.3461722', '-70.9055635');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Marcus House', 'Where Marcus Lives in first Film', '737 NW 15th Ave, Miami, FL 33125', 'Bad Boys', '1', '' , '');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Police Station', 'Dade Count courthouse', '73 W Flagler St, Miami, FL 33130', 'Bad Boys', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Club Hell', 'Marcus gets into a brawl in the bathroom', '471 NW 3rd St, Miami, FL 33128', 'Bad Boys', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Mikes Apartment', 'The apartment exterior where will smiths caracter lives', '2030 Park Ave, Miami Beach, FL 33139', 'Bad Boys', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Johnny Tapia Estate', 'Filmed at Vizcaya Museum and Gardens', '3251 S Miami Ave, Miami, FL 33129', 'Bad Boys II', '1', '41.470250', '-70.570340');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Miami Bank', 'Car chase where bodies in fall out of coffins.', '570 NE 81st St, Miami, FL 33138', 'Bad Boys II', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Mortuary', 'Macarthur Dairy Bulding, Mike and Marcus break in here.', '6851 NE 2nd Ave, Miami, FL 33138', 'Bad Boys II', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Opening Shot', 'Begins with a guitarist and drummer in front of a tree', '400 NW 73rd Ave, Plantation, FL 33317', 'There’s Something About Mary', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('HighSchool', 'Plantation City Hall was used for exterior shots of the school.', '400 NW 73rd Ave, Plantation, FL 33317', 'There’s Something About Mary', '1', '41.470250', '-70.570340');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Marys House', 'Located in Coral Gables Fl, where the notorious "zipper incident" happens', '3300 Granada Blvd, Coral Gables, FL 33134', 'There’s Something About Mary', '1', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Outside Marys workplace ', 'Where Ted finds Mary years later and hides behind sculpture.', '701 Brickell Ave, Miami, FL 33131', 'There’s Something About Mary', '1', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Hair Gel Scene', 'Where Mary meets Ted for their Date', '1300 Ocean Dr, Miami Beach, FL 33139', 'There’s Something About Mary', '1', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Closing Shots', 'Ted and Mary stand here facing the water', 'NE 20th Terrace / N Bayshore Dr, Miami, FL 33137', 'There’s Something About Mary', '1', '41.4161', '70.5487');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Birdcage Club', 'The Carlyle was used for the Club in the film', '1250 Ocean Dr, Miami Beach, FL 33139', 'The Birdcage', '1', '41.347680', '-70.744020');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Ending Conversation', 'The ending was filmed at Jimmys Eastside Diner', '7201 Biscayne Blvd, Miami, FL 331383', 'Moonlight', '1', '41.389640', '-70.514740');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Opening Shot', 'Reseda Theater where the opening was filmed', '18443 Sherman Way, Reseda, CA 91335', 'Boogie Nights', '1', '41.3892442', '-70.5479281');

INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Hot Traxx nightclub', 'Nightclub wher Rollegirl and Dirk works.', '18419 Sherman Way, Reseda, CA 91335', 'Boogie Nights', '1', '41.206150', '-86.594520');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Dirks Parents House', 'Located in Torrance California', '3503 187th St, Torrance, CA 90504', 'Boogie Nights', '1', '41.3893657', '-70.5833555');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Du-Pars Restaurant', 'Jack Horder takes Dirk here for a meal with Amber and Rollergirl.', '12036 Ventura Blvd, Studio City, CA 91604', 'Boogie Nights', '1', '41.3892155', '-70.514312');
INSERT INTO "Locations" ("Name", "Description", "Address", "Movie", "UserId", "Latitude", "Longitude") VALUES ('Jack Horners House', 'Several scenes shot here for the film', '19515 E Cameron Ave, Covina, CA 91724', 'Boogie Nights', '1', '41.3461722', '-70.9055635');



INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('House of 1000 Corpses ', 'Two young couples traveling across the backwoods of Texas searching for urban legends of murder end up as prisoners of a bizarre and sadistic backwater family of serial killers. ', '(2003)', 'https://theposterdb.com/api/assets/102851');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Social Network ', 'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea, and by the co-founder who was later squeezed out of the business. ', '(2010)', 'https://theposterdb.com/api/assets/64097');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Pulp Fiction ', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', '(1994)', 'https://theposterdb.com/api/assets/64097');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Reservoir Dogs', 'When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.', '(1992)', 'https://theposterdb.com/api/assets/38265');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Kill Bill', 'After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.', '(2003)', 'https://theposterdb.com/api/assets/82100');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Hateful Eight', 'In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters. ', '(2015)', 'https://theposterdb.com/api/assets/12753');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Once Upon a Time... In Hollywood', 'A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywoods Golden Age in 1969 Los Angeles. ', '(2019)', '');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Moonlight', 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.', '(2016)', '');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Zodiac', 'In the late 1960s/early 1970s, a San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer, an unidentified individual who terrorizes Northern California with a killing spree.', '(2007)', '');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Birdcage', 'A gay cabaret owner and his drag queen companion agree to put up a false straight front so that their son can introduce them to his fiancées right-wing moralistic parents.', '(1996)', '');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Boogie Nights', 'Back when sex was safe, pleasure was a business and business was booming, an idealistic porn producer aspires to elevate his craft to an art when he discovers a hot young talent.', '(1997)', 'https://theposterdb.com/api/assets/54119');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Se7en', 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.', '(1995)', 'https://theposterdb.com/api/assets/64091');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Back to the Future ', 'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.', '(1985)', 'https://theposterdb.com/api/assets/12302');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Baby Driver', 'After being coerced into working for a crime boss, a young getaway driver finds himself taking part in a heist doomed to fail.', '(2017)', 'https://theposterdb.com/api/assets/7407');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Bad Boys', 'Two hip detectives protect a witness to a murder while investigating a case of stolen heroin from the evidence storage room from their police precinct.', '(1995)', 'https://theposterdb.com/api/assets/38004');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Bad Boys II', 'Two loose-cannon narcotics cops investigate the flow of Ecstasy into Florida from a Cuban drug cartel.', '(2003)', 'https://theposterdb.com/api/assets/38005');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Theres Something About Mary', 'A man gets a chance to meet up with his dream girl from high school, even though his date with her back then was a complete disaster.', '(1998)', '');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Curious Case of Benjamin Button', 'Tells the story of Benjamin Button, a man who starts aging backwards with consequences.', '(2008)', 'https://theposterdb.com/api/assets/89001');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Mallrats', 'Both dumped by their girlfriends, two best friends seek refuge in the local mall.', '(1995)', 'https://theposterdb.com/api/assets/91863');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Jaws', 'When a killer shark unleashes chaos on a beach community, its up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.', '(1975)', 'https://theposterdb.com/api/assets/2436');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Dark Knight', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', '(2008)', 'https://theposterdb.com/api/assets/21708');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Dark Knight Rises', 'Eight years after the Jokers reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.', '(2012)', 'https://theposterdb.com/api/assets/21709');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Ferris Buellers Day Off ', 'A high school wise guy is determined to have a day off from school, despite what the Principal thinks of that.', '(1986)', 'https://theposterdb.com/api/assets/99153');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Ghostbusters', 'Three former parapsychology professors set up shop as a unique ghost removal service.', '(1984)', 'https://theposterdb.com/api/assets/7666');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Avengers', 'Earths mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.', '(2012)', 'https://theposterdb.com/api/assets/351');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Game', 'After a wealthy banker is given an opportunity to participate in a mysterious game, his life is turned upside down when he becomes unable to distinguish between the game and reality.', '(1997)', '');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Forrest Gump', 'The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.', '(1994)', 'https://theposterdb.com/api/assets/34064');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Into the Wild', 'After graduating from Emory University, top student and athlete Christopher McCandless abandons his possessions, gives his entire $24,000 savings account to charity and hitchhikes to Alaska to live in the wilderness. Along the way, Christopher encounters a series of characters that shape his life.', '(2007)', 'https://theposterdb.com/api/assets/81011');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Hunger Games: Catching Fire', 'Katniss Everdeen and Peeta Mellark become targets of the Capitol after their victory in the 74th Hunger Games sparks a rebellion in the Districts of Panem.', '(2013)', 'https://theposterdb.com/api/assets/6979');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Prisoners', 'When Keller Dovers daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts.', '(2013)', 'https://theposterdb.com/api/assets/64296');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Easy Rider', 'Two bikers head from L.A. to New Orleans through the open country and desert lands, and along the way they meet a man who bridges a counter-culture gap of which they had been unaware.', '(1969)', 'https://theposterdb.com/api/assets/41482');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Django Unchained', 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.', '(2012)', 'https://theposterdb.com/api/assets/8609');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Interview with the Vampire: The Vampire Chronicles', 'A vampire tells his epic life story: love, betrayal, loneliness, and hunger.', '(1994)', 'https://theposterdb.com/api/assets/34112');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('22 Jump Street', 'After making their way through high school (twice), big changes are in store for officers Schmidt and Jenko when they go deep undercover at a local college.', '(2014)', 'https://theposterdb.com/api/assets/22123');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Breakfast Club', 'Five high school students meet in Saturday detention and discover how they have a lot more in common than they thought. ', '(1985)'), 'https://theposterdb.com/api/assets/34395';
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Field of Dreams', 'An Iowa corn farmer, hearing voices, interprets them as a command to build a baseball diamond in his fields; he does, and the 1919 Chicago White Sox come.', '(1989)', 'https://theposterdb.com/api/assets/62828');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Fast Times at Ridgemont High', 'A group of Southern California high school students are enjoying their most important subjects: sex, drugs, and rock n roll.', '(1982)', 'https://theposterdb.com/api/assets/48090');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Fried Green Tomatoes', 'A housewife who is unhappy with her life befriends an old lady in a nursing home and is enthralled by the tales she tells of people she used to know.', '(1991)', 'https://theposterdb.com/api/assets/90810');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Grandmas Boy', 'A thirty-five-year-old video game tester has to move in with his grandma and her two old lady roommates.', '(2006)', 'https://theposterdb.com/api/assets/21722');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Groundhog Day', 'A weatherman finds himself inexplicably living the same day over and over again.', '(1993)', 'https://theposterdb.com/api/assets/68032');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Halloween', 'After being committed for 17 years, Michael Myers, now a grown man and still very dangerous, escapes from the mental institution and immediately returns to Haddonfield to find his baby sister, Laurie.', '(2007)', 'https://theposterdb.com/api/assets/8219');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Halloween', 'Fifteen years after murdering his sister on Halloween night 1963, Michael Myers escapes from a mental hospital and returns to the small town of Haddonfield, Illinois to kill again. ', '(1978)', 'https://theposterdb.com/api/assets/93085');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Heat', 'A group of professional bank robbers start to feel the heat from police when they unknowingly leave a clue at their latest heist.', '(1995)', 'https://theposterdb.com/api/assets/88578');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Home Alone', 'An eight-year-old troublemaker must protect his house from a pair of burglars when he is accidentally left home alone by his family during Christmas vacation.', '(1990)', 'https://theposterdb.com/api/assets/23879');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('High Fidelity', 'Rob, a record store owner and compulsive list maker, recounts his top five breakups, including the one in progress.', '(2000)', 'https://theposterdb.com/api/assets/58132');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Home Alone 2: Lost in New York', 'One year after Kevin McCallister was left home alone and had to defeat a pair of bumbling burglars, he accidentally finds himself stranded in New York City - and the same criminals are not far behind.', '(1992)', 'https://theposterdb.com/api/assets/23880');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Pretty in Pink', 'A poor girl must choose between the affections of dating her childhood sweetheart or a rich but sensitive playboy.', '(1986)', 'https://theposterdb.com/api/assets/49838');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Jackie Brown', 'A middle-aged woman finds herself in the middle of a huge conflict that will either make her a profit or cost her life.', '(1997)', 'https://theposterdb.com/api/assets/38267');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Jurassic Park', 'A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the parks cloned dinosaurs to run loose. ', '(1993)', 'https://theposterdb.com/api/assets/27535');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Rocky', 'A small-time boxer gets a supremely rare chance to fight a heavy-weight champion in a bout in which he strives to go the distance for his self-respect.', '(1976)', 'https://theposterdb.com/api/assets/78688');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', '(1994)', 'https://theposterdb.com/api/assets/64117');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Shining', 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.', '(1980)', 'https://theposterdb.com/api/assets/23730');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Town', 'A longtime thief, planning his next job, tries to balance his feelings for a bank manager connected to an earlier heist, and a hell-bent F.B.I Agent looking to bring him and his crew down.', '(2010)', 'https://theposterdb.com/api/assets/18647');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Poltergeist', 'A familys home is haunted by a host of demonic ghosts.', '(1982)', 'https://theposterdb.com/api/assets/26866');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Matinee', 'A small-time film promoter releases a kitschy horror film during the Cuban Missile Crisis.', '(1993)', 'https://theposterdb.com/api/assets/62829');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Kingpin', 'A star bowler whose career was prematurely "cut off" hopes to ride a new prodigy to success and riches.', '(1996)', 'https://theposterdb.com/api/assets/47826');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Departed', 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.', '(2006)', 'https://theposterdb.com/api/assets/97917');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Dogma', 'An abortion clinic worker with a special heritage is called upon to save the existence of humanity from being negated by two renegade angels trying to exploit a loop-hole and reenter Heaven.', '(1999)', 'https://theposterdb.com/api/assets/30362');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Drive', 'A mysterious Hollywood stuntman and mechanic moonlights as a getaway driver and finds himself in trouble when he helps out his neighbor in this action drama. ', '(2011)', 'https://theposterdb.com/api/assets/80559');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Good Will Hunting', 'Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life. ', '(1997)', 'https://theposterdb.com/api/assets/18349');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Risky Business', 'A Chicago teenager is looking for fun at home while his parents are away, but the situation quickly gets out of hand.', '(1983)', 'https://theposterdb.com/api/assets/79626');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Rock', 'A mild-mannered chemist and an ex-con must lead the counterstrike when a rogue group of military men, led by a renegade general, threaten a nerve gas attack from Alcatraz against San Francisco.', '(1996)', 'https://theposterdb.com/api/assets/76065');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Stand by Me', 'After the death of one of his friends, a writer recounts a childhood journey with his friends to find the body of a missing boy.', '(1986)', 'https://theposterdb.com/api/assets/66160');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Doc Hollywood', 'A young doctor on his wAce Ventura: Pet Detective (1994)ay across the country to a job interview crashes his car in a small town and is sentenced to work for several days at the town hospital.', '(1991)', '');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Edward Scissorhands', 'An artificial man, who was incompletely constructed and has scissors for hands, leads a solitary life. Then one day, a suburban lady meets him and introduces him to her world.', '(1990)', 'https://theposterdb.com/api/assets/36116');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Magic Mike', 'A male stripper teaches a younger performer how to party, pick up women, and make easy money', '(2012)', 'https://theposterdb.com/api/assets/46679');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('My Girl', 'A young girl, on the threshold of her teen years, finds her life turning upside down, when she is accompanied by an unlikely friend.', '(1991)', 'https://theposterdb.com/api/assets/62861');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Ace Ventura: Pet Detective', 'A goofy detective specializing in animals goes in search of the missing mascot of the Miami Dolphins.', '(1994)', 'https://theposterdb.com/api/assets/51652');

INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('The Florida Project', 'Set over one summer, the film follows precocious six-year-old Moonee as she courts mischief and adventure with her ragtag playmates and bonds with her rebellious but caring mother, all while living in the shadows of Walt Disney World.', '(2017)', 'https://theposterdb.com/api/assets/90031');
INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('Fight Club', 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.', '(1999)', 'https://theposterdb.com/api/assets/35829');

-- INSERT INTO "Films" ("Title", "Description", "Year", "Poster") VALUES ('', '', '', '');



 
-- INSERT INTO "Reviews" ("LocationId", "CreatedAt", "Summary", "Body", "Stars") VALUES (1, '2020-01-01 14:23:55', 'Awesome', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima modi impedit quisquam sit, saepe enim placeat a vero voluptas asperiores atque laudantium in, nobis sunt blanditiis dignissimos. Deleniti, esse optio!', 3);
-- INSERT INTO "Reviews" ("LocationId", "CreatedAt", "Summary", "Body", "Stars") VALUES (1, '2020-01-01 18:23:55', 'Lots to see!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima modi impedit quisquam sit, saepe enim placeat a vero voluptas asperiores atque laudantium in, nobis sunt blanditiis dignissimos. Deleniti, esse optio!', 4);