TRUNCATE TABLE "Locations", "Reviews" RESTART IDENTITY;

INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude")  VALUES ('The Brody House', 'The house featured in the production has been completely renovated, but this is still Chief Martin Brodys address.', '265 East Chop Dr Vineyard Haven, Mass.', '314-651-9791', '41.470250', '-70.570340');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Amity Police Department', 'Where Brody Types up the "shark Attack" police report', 'South Water Street & Davis Lane Edgartown, MA 02539', '523-760-6681', '41.3884781', '-70.5488173');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Amity Hardware', 'Brody grabs supplies for his "Beach Closed" mission at Amity Hardware and then walks through the center of town.', 'South Water Street & Main Street Edgartown, Mass.', '650-993-7074', '41.389430', '-70.513050');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('The Beach', 'Where Alex Kitner is eaten', 'Joseph Sylvia State Beach Oak Bluffs, Mass.', '715-663-5265', '41.4215675', '-70.6225625');

INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('The Bridge', 'Bridge from beach to pond', 'American Legion Memorial Bridge', '314-651-9791', '41.4161', '70.5487');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Quint Shack', 'While his workshop was built for the production and no longer standing, the adorable fishing village/tourist haven of Menemsha remains', 'Menemsha Port Chilmark, Mass.', '523-760-6681', '41.347680', '-70.744020');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Amity Town Hall', 'Interior and eterior of Amity town hall', ' 70 Main Street Edgartown, Mass.', '650-993-7074', '41.389640', '-70.514740');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Vaughn Realty', 'Mayor Vaughn exterior location', '1 Water Street Edgartown, Mass.', '715-663-5265', '41.3892442', '-70.5479281');

INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('The Opening Scene', 'Beach bonfire and the demise of Chrissie Watkins.', 'South Beach Edgartown, Mass', '314-651-9791', '41.206150', '-86.594520');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Keisel Bicycle Rental & Amity Gazette', 'The Gazette and Bicycle rental are located across from oneanother. Shop owner complains about kids karate chopping fences', '2 South Water Street Edgartown, MA 02539', '523-760-6681', '41.3893657', '-70.5833555');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Chappy Ferry', 'The ferry worked as both a principal camera boat for the production and starred in the scene where Brody is browbeaten by the mayor into keeping the beaches open for the Fourth. You know, for the tourists. "Martin, its all psychological. You yell barracuda, everybody says, "Huh? What?" You yell shark, weve got a panic on our hands on the Fourth of July."', '53 Dock Street Edgartown, MA 02539', '650-993-7074', '41.3892155', '-70.514312');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Billboard/Lighthouse', 'Where Brody and Vaughn argue about keeping beaches open', '35 Aquinnah Circle Aquinnah, MA 02535', '715-663-5265', '41.3461722', '-70.9055635');

INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Wacker Drive', 'A major multilevel 2.2 mile stretch in lower Chicago, running along the south side of the main branch and the east side of the south branch of the Chicago River in the Loop.', '233 E Wacker Dr, Chicago, IL 60601', '314-651-9791', '41.8877172', '-87.691257');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('The Old Main Post Office', 'Used in Batman Begins and The Dark Knight as Gotham Police Department', '433 W Van Buren St, Chicago, IL 60607', '523-760-6681', '41.8755587', '-87.7088813');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Chicago Board of Trade', 'The Chicago Board of Trade building is an iconic Art Deco skyscraper on West Jackson Boulevard. In film, it stood in as Bruce Wayne’s corporate HQ in Batman Begins. One of its trading floors was shown in Ferris Buellers day Off, also featured in several scenes in The Untouchables.', '141 W Jackson Blvd, Chicago, IL 60604', '650-993-7074', '41.8780309', '-87.6367784');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Art Institute of Chicago', 'Ferris and his friends take on the streets of Chicago, with a drop-by at the Art Institute of Chicago.', '111 S Michigan Ave, Chicago, IL 60603', '715-663-5265', '41.8795473', '-87.6259125');

INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Union Station', 'As one of Chicago’s most iconic and historical landmarks, Union Station serves as backdrop to various scenes in movie history. It’s the citys primary terminal for commuter trains, covering over 9 city blocks underneath Chicago’s network of streets and skyscrapers.', '225 S Canal St, Chicago, IL 60606', '314-651-9791', '41.8785772', '-87.6418552');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Wrigley Field', 'Wrigley Field is promently featured in several films, such as Ferris Beullers Day Off, A League of Their Own, and Rookie of the Year', '1060 W Addison St, Chicago, IL 60613', '523-760-6681', '41.9474552', '-87.6604312');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('The Fireside Bowl', ' The retro-styled bowling alley has not only hosted serious bowlers for ages, it was also the nexus of Chicago’s punk scene for many years. It is featured in The Break Up', 'S2646 W Fullerton Ave, Chicago, IL 60647', '650-993-7074', '41.9248404', '-87.7092263');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('South LaSalle St', 'Transformed, and featured in the period piece Road to Perdition', 'S LaSalle St Chicago, IL', '715-663-5265', '41.8770717', '-87.6405164');

INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('New York Public Library', 'Prominently feature in Ghostbusters, The Day After Tomorrow, Breakfast at Tiffanys Sex and the City: the Movie and Spider-Man', '476 Fifth Avenue, Manhattan, New York', '314-651-9791', '40.7531903', '-73.9866308');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Times Square', 'Featured in numerous films, Taxi Driver, Midnight Cowboy, Date Night, Captain America, Big, Shaft, A Chorus Line, Vanilla Sky, Birdman… ', 'Manhattan, NY 10036', '523-760-6681', '40.7580836', '-74.0555823');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Hook and Ladder 8', 'Who you gonna call?', '14 N Moore St, New York, NY 10013', '650-993-7074', '40.7196745', '-74.0766521');
INSERT INTO "Locations" ("Name", "Description", "Address", "Telephone","Latitude", "Longitude") VALUES ('Grand Central Terminal', 'A transportation hub for travellers and commuters since 1913, Grand Central Terminal has been featured in numerous films such as, Carlitos way, The Avengers, and North by Northwest', '89 E 42nd St, New York, NY 10017', '715-663-5265', '40.7528366', '-74.047275');

INSERT INTO "Reviews" ("LocationId", "CreatedAt", "Summary", "Body", "Stars") VALUES (1, '2020-01-01 14:23:55', 'Awesome', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima modi impedit quisquam sit, saepe enim placeat a vero voluptas asperiores atque laudantium in, nobis sunt blanditiis dignissimos. Deleniti, esse optio!', 3);
INSERT INTO "Reviews" ("LocationId", "CreatedAt", "Summary", "Body", "Stars") VALUES (1, '2020-01-01 18:23:55', 'Lots to see!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima modi impedit quisquam sit, saepe enim placeat a vero voluptas asperiores atque laudantium in, nobis sunt blanditiis dignissimos. Deleniti, esse optio!', 4);